# Generated by Django 5.2.11 on 2026-02-25 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_interest_remove_person_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
        ),
    ]
