# Generated by Django 5.2.11 on 2026-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_interest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
    ]
